---
title: "question6"
output: html_document
---

```{r question6, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

# Question 6
Comment on the summary statistics and distribution of the ABV variable.
```{r}
summary(merged$ABV)
summary(merged$ABVfill)
sd(merged$ABV,na.rm=TRUE)
sd(merged$ABVfill)
```

The mean is slightly higher than the median, which would indicate a right skewed distribution,
one with a long tail of high values.

```{r}
merged %>% drop_na(ABV) %>%
  ggplot(aes(x=ABV)) + geom_histogram(aes(y=..density..),bins=27) + 
  ggtitle('Histogram and density estimate of ABV values (no infilling)') +
  geom_vline(aes(xintercept=median(ABV)),color='blue',linetype='dashed',size=1) +
  geom_text(mapping=aes(x=median(ABV),y=40,label="median"),
            color="blue",angle=90,vjust=-0.4,show.legend=FALSE) +
  geom_vline(aes(xintercept=mean(ABV)), color='red',linetype='dotted',size=1) +
  geom_text(mapping=aes(x=mean(ABV),y=40,label="mean"),
            color="red",angle=90,vjust=-0.4,show.legend=FALSE) +
  geom_density(alpha=.2,fill="#FF6666")
```

```{r}
merged %>% 
  ggplot(aes(x=ABVfill)) + geom_histogram(aes(y=..density..),bins=27) + 
  ggtitle('Histogram and density estimate of ABV values (missing values inferred)') +
  geom_vline(aes(xintercept=median(ABVfill)),color='blue',linetype='dashed',size=1) +
  geom_text(mapping=aes(x=median(ABVfill),y=40,label="median"),
            color="blue",angle=90,vjust=-0.4,show.legend=FALSE) +
  geom_vline(aes(xintercept=mean(ABVfill)), color='red',linetype='dotted',size=1) +
  geom_text(mapping=aes(x=mean(ABVfill),y=40,label="mean"),
            color="red",angle=90,vjust=-0.4,show.legend=FALSE) +
  geom_density(alpha=.2,fill="#FF6666")
```

The histogram bears this out.

Out of curiosity, repeat this for IBU

```{r}
summary(merged$IBU)
summary(merged$IBUfill)
```

```{r}
merged %>% drop_na(IBU) %>%
  ggplot(aes(x=IBU)) + geom_histogram(aes(y=..density..),bins=27) + 
  ggtitle('Histogram of IBU values (no infilling)') +
  geom_vline(aes(xintercept=median(IBU)),color='blue',linetype='dashed',size=1) +
  geom_text(mapping=aes(x=median(IBU),y=.022,label="median"),
            color="blue",angle=90,vjust=-0.4,show.legend=FALSE) +
  geom_vline(aes(xintercept=mean(IBU)), color='red',linetype='dotted',size=1) +
  geom_text(mapping=aes(x=mean(IBU),y=.022,label="mean"),
            color="red",angle=90,vjust=-0.4,show.legend=FALSE) +
  geom_density(alpha=.2,fill="#FF6666")
```

```{r}
merged %>%
  ggplot(aes(x=IBUfill)) + geom_histogram(aes(y=..density..),bins=27) + 
  ggtitle('Histogram of IBU values (missing values inferred)') +
  geom_vline(aes(xintercept=median(IBUfill)),color='blue',linetype='dashed',size=1) +
  geom_text(mapping=aes(x=median(IBUfill),y=.022,label="median"),
            color="blue",angle=90,vjust=-0.4,show.legend=FALSE) +
  geom_vline(aes(xintercept=mean(IBUfill)), color='red',linetype='dotted',size=1) +
  geom_text(mapping=aes(x=mean(IBUfill),y=.022,label="mean"),
            color="red",angle=90,vjust=-0.4,show.legend=FALSE) +
  geom_density(alpha=.2,fill="#FF6666")
```


