---
title: "question9"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r question9, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(BBmisc)
```

# Question 9
Knocking their socks off.
```{r}
#cleaning house:
merged$State <- str_trim(merged$State, "left")

# basic EDA
style_count <- merged %>% group_by(Style) %>% summarize(n = n()) %>% arrange(desc(n))
style_count %>% filter(n > 50) %>% ggplot(aes(x=reorder(Style, desc(n)), y = n)) +
  geom_bar(stat="identity", fill = "#C8102E") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  labs(title="10 Most Common Styles of Craft Brews", x="", y="Count")

# 1. find the most popular beers in each state
# 2. find the states that have lower than median breweries per capita
# 3. find states with > 5M total population
# 4. identify the most popular beer style in each of those states
# 5. run k-means clustering to group states by feature combinations

# get the 1st, 2nd, and 3rd most popular beers per state
stateabbr <- unique(merged$State)
popular1 <- c()
popular2 <- c()
popular3 <- c()
for (i in 1:length(stateabbr))
{
  temp <- merged %>% 
    filter(State==stateabbr[i]) %>% 
    group_by(Style) %>% 
    summarize(n=n()) %>% 
    arrange(desc(n))
  
  popular1[i] <- as.character(temp$Style)[1]
  popular2[i] <- as.character(temp$Style)[2]
  popular3[i] <- as.character(temp$Style)[3]
}

q9 <- data.frame(State = stateabbr, P1 = popular1, P2 = popular2, P3 = popular3)

style_count_bystate <- merged %>% group_by(State) %>% summarize(nStyles = n_distinct(Style))
q9 <- merge(q9, style_count_bystate, by="State")

tempbrewery <- breweries_raw %>%  group_by(State) %>% summarize(breweryCount = n())
q9$breweryCount <- tempbrewery$breweryCount

temp <- statepop
temp$State <- temp$abbr
q9 <- merge(q9,temp, by="State")

q9$nBreweriesPerCapita = q9$breweryCount/q9$pop_2015

# which states have populations > 5,000,000
q9$gt5M <- "lt5M"
q9$gt5M[which(q9$pop_2015 > 5000000)] = "gt5M"

# which states have below average breweries per Capita
q9$belowperCapita <- "gtMedian"
q9$belowperCapita[which(q9$nBreweriesPerCapita < median(q9$nBreweriesPerCapita, na.rm=TRUE))] = "ltMedian"

# q9$state <- states_and_dc$state

q9$target <- "no"
q9$target[which(q9$gt5M == "gt5M" & q9$belowperCapita == "ltMedian")] = "yes"

# state land area in square miles
temp <- data.frame(State = state.abb, LandArea = state.area)
q9 <- merge(q9,temp, by="State")

q9$nStylesPerCapita <- q9$nStyles/(q9$pop_2015/1000000)
q9$PopulationPerSqMile <- q9$pop_2015/q9$LandArea
q9$nBreweriesPerSqMile <- q9$breweryCount/(q9$LandArea/1000)

# intersection of population and breweries per capita
q9$popular1st <- "N/A"
q9$popular1st[which(q9$gt5M == "gt5M" & q9$belowperCapita == "ltMedian")] = 
  as.character(q9$P1[which(q9$gt5M == "gt5M" & q9$belowperCapita == "ltMedian")])

q9$popular2nd <- "N/A"
q9$popular2nd[which(q9$gt5M == "gt5M" & q9$belowperCapita == "ltMedian")] = 
  as.character(q9$P2[which(q9$gt5M == "gt5M" & q9$belowperCapita == "ltMedian")])

q9$popular3rd <- "N/A"
q9$popular3rd[which(q9$gt5M == "gt5M" & q9$belowperCapita == "ltMedian")] = 
  as.character(q9$P3[which(q9$gt5M == "gt5M" & q9$belowperCapita == "ltMedian")])

####################################################
#### mapping
# library(usmap)
# library(ggthemes)

plot_usmap(regions = c("states"), data = q9,
  values = "gt5M", theme = theme_map(), labels = FALSE,
  label_color = "black") + 
  theme(legend.position="right") +
  scale_fill_manual(name = "", values=c("grey","white")) +
  labs(title = 'States with Population of 5M or greater')

plot_usmap(regions = c("states"), data = q9,
  values = "belowperCapita", theme = theme_map(), labels = FALSE,
  label_color = "black") + 
  theme(legend.position="right") +
  scale_fill_manual(name = "", values=c("white","navyblue")) +
  labs(title = 'States with lower than median Breweries per Capita')

plot_usmap(regions = c("states"), data = q9,
  values = "target", theme = theme_map(), labels = FALSE,
  label_color = "black") + 
  theme(legend.position="right") +
  scale_fill_manual(name = "", values=c("white","red")) +
  labs(title = 'States to Target')

plot_usmap(regions = c("states"), data = q9,
  values = "popular1st", theme = theme_map(), labels = FALSE,
  label_color = "black") + 
  theme(legend.position="right") +
  scale_fill_manual(name = "Style", values=c("white","red","blue","darkgray")) +
  labs(title = 'Most Frequent Beer Style')

plot_usmap(regions = c("states"), data = q9,
  values = "popular2nd", theme = theme_map(), labels = FALSE,
  label_color = "black") + 
  theme(legend.position="right") +
  scale_fill_manual(name = "Style", values=c("green","white","red","blue","darkgray")) +
  labs(title = '2nd Most Frequent Beer Style')

plot_usmap(regions = c("states"), data = q9,
  values = "popular3rd", theme = theme_map(), labels = FALSE,
  label_color = "black") + 
  theme(legend.position="right") +
  scale_fill_manual(name = "Style", values=c("green","white","red","blue","navyblue","red3","grey","blue4","darkgray")) +
  labs(title = '3rd Most Frequent Beer Style')


plot_usmap(regions = c("states"), data = q9,
  values = "P1", theme = theme_map(), labels = FALSE,
  label_color = "black") + 
  theme(legend.position="right") +
  scale_fill_manual(name = "Style", values=c("green","white","red","blue","navyblue","red3","grey","blue4","seagreen1","darkgray","slateblue3","yellow2")) +
  labs(title = 'Most Frequent Beer Style')


##################################################
### https://uc-r.github.io/kmeans_clustering
### retry k-means with new variables
forkmeans <- q9 %>% select(nBreweriesPerCapita, nBreweriesPerSqMile, nStylesPerCapita)
row.names(forkmeans) <- q9$State

# # k-means clustering
# # find optimal "k"
# library(factoextra)
fviz_nbclust(forkmeans, kmeans, method="wss")
# 
set.seed(10)
brewsCluster <- kmeans(forkmeans, 2, nstart=20)
str(brewsCluster)
brewsCluster$cluster
cluster_container = c()
for (i in 1:length(brewsCluster$cluster))
{
  cluster_container[i] <- brewsCluster$cluster[[i]]
}
# visualize clusters plotted with Principle Component (?) axes
fviz_cluster(brewsCluster, forkmeans)

forkmeans_tomap <- forkmeans
forkmeans_tomap$cluster <- cluster_container
# forkmeans_tomap$fips <- statesvar
forkmeans_tomap$state <- q9$State
forkmeans_tomap$cluster <- as.factor(forkmeans_tomap$cluster)

# # 
plot_usmap(regions = c("states"), data = forkmeans_tomap,
  values = "cluster", theme = theme_map(), labels = FALSE,
  label_color = "black") +
  scale_fill_manual(values=c("red","blue","grey","white"))

forkmeans_tomap %>% ggplot(aes(x=nBreweriesPerSqMile, y=nStylesPerCapita, col=cluster)) +
  geom_point()


##########
##########
##########

##########
### retry k-means with new variables

merged$ratio <- merged$IBU/merged$ABV

ia_ratio <- merged %>%
  group_by(State) %>%
  summarize(ia_ratio = median(ratio, na.rm=TRUE))
medianabv <- merged %>%
  group_by(State) %>%
  summarize(medianabv = median(ABV, na.rm=TRUE))
medianibu <- merged %>%
  group_by(State) %>%
  summarize(medianibu = median(IBU, na.rm=TRUE))

m1 <- merge(ia_ratio, medianabv, by="State")
m2 <- merge(m1, medianibu, by="State")
q9 <- merge(q9, m2, by="State")

nBreweries <- merged %>%
  group_by(State) %>%
  summarize(nBreweries = length(unique(as.character(Brewery_name))))

q9 <- merge(q9,nBreweries, by="State")
q9$nStylesPerBrewery <- q9$nStyles/q9$nBreweries


forkmeans <- q9 %>% select(medianabv, medianibu, ia_ratio, nStylesPerCapita)
# forkmeans <- q9 %>% select(nBreweriesPerSqMile,nStylesPerCapita, medianabv, medianibu, ia_ratio)

# https://www.rdocumentation.org/packages/BBmisc/versions/1.10/topics/normalize
# library(BBmisc)
forkmeans_s <- normalize(forkmeans, method = "standardize")

row.names(forkmeans_s) <- q9$State
row.names(forkmeans) <- q9$State

forkmeans_s$target <- NA
forkmeans$target <- NA
forkmeans_s$target[which(q9$target == "yes")] = 1
forkmeans$target[which(q9$target == "yes")] = 1

forkmeans <- na.omit(forkmeans)
forkmeans_s <- na.omit(forkmeans_s)

forkmeans$target <- NULL
forkmeans_s$target <- NULL


# # k-means clustering
# # find optimal "k"
# library(factoextra)
fviz_nbclust(forkmeans_s, kmeans, method="wss")
# 
set.seed(10)
brewsCluster <- kmeans(forkmeans_s, 4, nstart=20)
str(brewsCluster)
brewsCluster$cluster
cluster_container = c()
for (i in 1:length(brewsCluster$cluster))
{
  cluster_container[i] <- brewsCluster$cluster[[i]]
}
# visualize clusters plotted with Principle Component (?) axes
fviz_cluster(brewsCluster, forkmeans_s)

forkmeans_tomap <- forkmeans
forkmeans_tomap$cluster <- cluster_container
# forkmeans_tomap$fips <- statesvar
forkmeans_tomap$state <- q9$State[which(q9$target == "yes")]
forkmeans_tomap$nStylesPerCapita <- q9$nStylesPerCapita[which(q9$target == "yes")]
forkmeans_tomap$cluster <- as.factor(forkmeans_tomap$cluster)

# # 
plot_usmap(regions = c("states"), data = forkmeans_tomap,
  values = "cluster", theme = theme_map(), labels = FALSE,
  label_color = "black") +
  scale_fill_manual(values=c("red","blue","yellow","green", "white")) +
  labs(title = "K-Means Clustering of Target States")

forkmeans_tomap %>% ggplot(aes(x=medianabv, y=medianibu, col=cluster, label=row.names(forkmeans_tomap))) +
  geom_text() +
  labs(x='median ABV', y = 'median IBU')

forkmeans_tomap %>% ggplot(aes(x=nStylesPerCapita, y=ia_ratio, col=cluster, label=row.names(forkmeans_tomap))) +
  geom_text() +
  labs(x='Styles per Capita', y = 'Number of Styles Currently Brewed')
```
